import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { ContactInfo } from "@/components/ContactInfo";
import { SectionLayout } from "@/components/SectionLayout";
import { FrontPage } from "@/components/FrontPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>WANG Intviational</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FrontPage />
      <Box>
        En samling for de mest ivrige først 2007 og 2008. Spillerne blir
        invitert så ingen påmelding Kontaktinfo
        <SectionLayout>
          <ContactInfo />
        </SectionLayout>
      </Box>
    </>
  );
}
